### PR TITLE
Fix instaddict for 2024

### PR DESCRIPTION
**Pull request by jazzathedev**
This fixes it at least partly. There is probably more that has broken, but this handles most of it.

### CODE REVIEW

**Review by Androz2091 — CHANGES_REQUESTED** [review]
Thank you so much for your PR! That's crazy work. Could you not change the formatting of the whole project please? It's very hard to review

**Comment by jazzathedev** [comment]
> Thank you so much for your PR! That's crazy work. Could you not change the formatting of the whole project please? It's very hard to review

Oh yeah sorry that's prettier, do you have a prettier config file I can use?

**Comment by Androz2091** [comment]
No I'm really sorry. Would it be fine to just undo the formatting changes?

**Comment by jazzathedev** [comment]
I honestly don't know if I can (im rather new to programming, took me a good hour to learn how to do this) but ill look into it

**Review by Androz2091 — COMMENTED** [review]
LGTM, thank you very much for your contribution

**Pull request merged**
